version: '3.1'
services:
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: postgres
    volumes:
       - /home/coding/dev/repo/church-check-in-all/Docker/PostgresData:/var/lib/postgresql/data
